# 1.20.6

TALL_GRASS = None
TARGET = None
TINTED_GLASS = None
TNT = None
TORCHFLOWER = None
TORCHFLOWER_CROP = None
TRAPPED_CHEST = None
TRIPWIRE = None
TRIPWIRE_HOOK = None
TUFF = None
TURTLE_EGG = None
TWISTING_VINES = None
TWISTING_VINES_PLANT = None
VOID_AIR = None
WARPED_WART_BLOCK = None
WATER = None
WEEPING_VINES = None
WEEPING_VINES_PLANT = None
WHEAT = None
WITHER_ROSE = None
